/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import Dao.Daos.DaoProducto;
import Dao.Modelo.Producto;
import Dao.Modelo.Usuarios;
import Recursos.ElementosPersonalizados.*;
import Recursos.*;
import static Recursos.Fechas.formatearFecha;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 * FALTA IMPLEMNTAR
 *
 * @author HugoJB
 */
public class CategoriaProducto extends javax.swing.JFrame {
    // private com.github.lgooddatepicker.components.DatePicker FechaPicker;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CategoriaProducto.class.getName());
    private final Usuarios user;
    List<Producto> productos;
    Boolean cat;

    /**
     * Creates new form CategoriaProducto
     */
    public CategoriaProducto(Usuarios user, List<Producto> productosm, Boolean categoria) {
        //  FechaPicker = new com.github.lgooddatepicker.components.DatePicker();
        ResurceBundle.setLocale(ResurceBundle.spanish);
        initComponents();
        getContentPane().setBackground(new Color(30, 30, 35));   // en el JFrame
// o en tu panel principal:
//panelPrincipal.setBackground(new Color(30, 30, 35));
        this.user = user;

        if (user == null) {
            CuadroDiologo.mostrarAviso(this, "Sin usuario no se puede ejecutar", "no se pude seguir", JOptionPane.ERROR_MESSAGE);
            //System.exit(1); //ME CARGO EL PROGAMA 
            //MEJOR ME VOY AL LOGIN
            this.dispose();
            InicioSesion inicioSesion = new InicioSesion();
            inicioSesion.setVisible(true);//VA INICIO SESION
            //  System.exit(0);
            return;
        }
        this.productos = productos;
        this.cat = categoria;
        actualizarElementosIdioma();
        actualizarList();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new LabelTitulo("");
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new TableBonito();
        Añadir1 = new BotonBonito("");
        Restar1 = new BotonBonito("");
        VerProducto = new BotonBonito("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setText("fedsqwwgfdssdggsdgsdfgg");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                ResurceBundle.t("table.product.name") , ResurceBundle.t("table.product.category"),  ResurceBundle.t("table.product.quantity"),  ResurceBundle.t("table.product.minQuantity"),ResurceBundle.t("label.dateExpiraton")
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class,java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false,false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.getViewport().setBackground(new Color(45, 45, 55));
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(80, 80, 95)));

        Añadir1.setText("jButton1");
        Añadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Añadir1ActionPerformed(evt);
            }
        });

        Restar1.setText("jButton1");
        Restar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restar1ActionPerformed(evt);
            }
        });

        VerProducto.setText("jButton1");
        VerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Añadir1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addGap(52, 52, 52)
                        .addComponent(Restar1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(VerProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Añadir1)
                    .addComponent(Restar1))
                .addGap(18, 18, 18)
                .addComponent(VerProducto)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Añadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Añadir1ActionPerformed
        // TODO add your handling code here:
        Controlador.modifiacarCantidad(cogerElementoActual(), 1); actualizarList();
    }//GEN-LAST:event_Añadir1ActionPerformed

    private void Restar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restar1ActionPerformed
        // TODO add your handling code here:
           Controlador.modifiacarCantidad(cogerElementoActual(), -1);actualizarList();

    }//GEN-LAST:event_Restar1ActionPerformed

    private void VerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerProductoActionPerformed
        // TODO add your handling code here:
        Producto p = cogerElementoActual();
        if (p == null) {
            return;

        }
        this.dispose();
        ProductoFicha pr = new ProductoFicha(p,user);
        pr.setVisible(true);
        pr.setLocationRelativeTo(null);
    }//GEN-LAST:event_VerProductoActionPerformed
    private Producto cogerElementoActual() {
        if (productos == null || productos.isEmpty()) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.noProducts.title"), // "Error"
                    ResurceBundle.t("dialog.noProducts.message"), // "No hay productos en la lista"
                    JOptionPane.ERROR_MESSAGE
            );
            return null;
        }

        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.noSelection.title"), // "Sin selección"
                    ResurceBundle.t("dialog.noSelection.message"), // "Selecciona un producto de la tabla"
                    JOptionPane.INFORMATION_MESSAGE
            );
            return null;
        }

        int filaModelo = jTable1.convertRowIndexToModel(fila);
        return productos.get(filaModelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CategoriaProducto(null, null, false).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añadir1;
    private javax.swing.JButton Restar1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VerProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void actualizarElementosIdioma() {
        /* Titulo.setText(ResurceBundle.t("login.title"));
        UserLabel.setText(ResurceBundle.t("label.userOrEmail"));
        userPane.setToolTipText(ResurceBundle.t("tooltip.userOrEmail"));
        password.setText(ResurceBundle.t("label.password"));        
        passwordPane.setToolTipText(ResurceBundle.t("tooltip.password"));
        Enviar.setText(ResurceBundle.t("button.next"));
        recuperarContrasenaBotton.setText(ResurceBundle.t("button.recoverPassword"));
        nuevoUsuario.setText(ResurceBundle.t("button.newUser"));*/
        //   adir1.setText(ResurceBundle.t("button.add"));                  // Añadir
        //AñadirListaCompra.setText(ResurceBundle.t("label.shoppingList"));// Ver lista de compra
        //EliminarProducto.setText(ResurceBundle.t("button.delete"));      // Eliminar
        if (cat) {
            Titulo.setText(ResurceBundle.t("label.category"));

        } else {
            Titulo.setText(ResurceBundle.t("label.results"));//CUANDO VIENE DE RESULTADOS

        }
        Añadir1.setText(ResurceBundle.t("button.add"));                  // Añadir

        Restar1.setText(ResurceBundle.t("button.decreaseQuantity"));
        VerProducto.setText(ResurceBundle.t("label.viewByProduct"));                  // Añadir

    }

    private void actualizarList() {
        if (productos == null || productos.isEmpty()) {
            CuadroDiologo.mostrarAviso(this, "Error", "No hay elementos que mostrar vuelve a la pantalla princiapal", JOptionPane.ERROR);
            return;
        }
        if (productos == null || productos.isEmpty()) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.noResults.title"), // o texto directo
                    ResurceBundle.t("dialog.noResults.message"), // "No hay elementos que mostrar..."
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Obtener el modelo de la tabla
        javax.swing.table.DefaultTableModel modelo
                = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        // Limpiar la tabla
        modelo.setRowCount(0);

        // Rellenar filas desde la lista productos
        for (Producto p : productos) {

            modelo.addRow(new Object[]{
                p.getNombre(),
                p.getIdCategoria().getNombre(), // categoría
                p.getCantidad(),
                p.getCantidadMinDeseada(),
                Fechas.formatearFecha(p.getFechaCaducidad())
            });
        }
    }

    
}
