/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import Dao.Daos.DaoProducto;
import Dao.Modelo.Producto;
import Dao.Modelo.Usuarios;
import Recursos.ElementosPersonalizados.*;
import Recursos.*;
import static Recursos.Fechas.formatearFecha;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 * Pantalla de visualización y gestión de productos por categoría o resultados de búsqueda. Permite al usuario ver productos en tabla, aumentar/disminuir cantidad y acceder a detalles.
 *
 * @author HugoJB
 */
public class CategoriaProducto extends javax.swing.JFrame {
    // private com.github.lgooddatepicker.components.DatePicker FechaPicker;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CategoriaProducto.class.getName());
    private final Usuarios user;
    List<Producto> productos;
    Boolean cat;

    /**
     * Constructor que inicializa la ventana de categoría de productos. Valida que el usuario no sea nulo, configura idioma y rellena la tabla.
     *
     * @param user Usuario autenticado (requerido, si es null redirige a login)
     * @param productosm Lista de productos a mostrar en la tabla
     * @param categoria true si muestra categoría, false si muestra resultados de búsqueda
     * @param idioma Código de idioma (ej: "es", "en") para localización
     */
    public CategoriaProducto(Usuarios user, List<Producto> productosm, Boolean categoria, String idioma) {

        //  FechaPicker = new com.github.lgooddatepicker.components.DatePicker();
        initComponents();
        getContentPane().setBackground(new Color(30, 30, 35));   // en el JFrame
// o en tu panel principal:
//panelPrincipal.setBackground(new Color(30, 30, 35));
        this.user = user;

        if (user == null) {
            CuadroDiologo.mostrarAviso(this, "Sin usuario no se puede ejecutar", "no se pude seguir", JOptionPane.ERROR_MESSAGE);
            //System.exit(1); //ME CARGO EL PROGAMA 
            //MEJOR ME VOY AL LOGIN
            this.dispose();
            InicioSesion inicioSesion = new InicioSesion(idioma);
            inicioSesion.setVisible(true);//VA INICIO SESION
            //  System.exit(0);
            return;
        }
        ResurceBundle.setLocale(idioma);

        this.productos = productosm;
        this.cat = categoria;
        actualizarElementosIdioma();
        actualizarList();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new LabelTitulo("");
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new TableBonito();
        Añadir1 = new BotonBonito("");
        Restar1 = new BotonBonito("");
        VerProducto = new BotonBonito("");
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        Acesebilidad = new javax.swing.JMenu();
        CambioIdioma = new javax.swing.JMenu();
        Español = new javax.swing.JMenuItem();
        Ingles = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenu();
        jMenuItem1Buscar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setText("fedsqwwgfdssdggsdgsdfgg");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                ResurceBundle.t("table.product.name") , ResurceBundle.t("table.product.category"),  ResurceBundle.t("table.product.quantity"),  ResurceBundle.t("table.product.minQuantity"),ResurceBundle.t("label.dateExpiraton")
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class,java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false,false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.getViewport().setBackground(new Color(45, 45, 55));
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(80, 80, 95)));

        Añadir1.setText("jButton1");
        Añadir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Añadir1ActionPerformed(evt);
            }
        });

        Restar1.setText("jButton1");
        Restar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restar1ActionPerformed(evt);
            }
        });

        VerProducto.setText("jButton1");
        VerProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerProductoActionPerformed(evt);
            }
        });

        jMenu1.setText("Ir a");

        jMenuItem2.setText("Menu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        Acesebilidad.setText("Acesibilidad");

        CambioIdioma.setText("jMenu2");

        Español.setText("jMenuItem1");
        Español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspañolActionPerformed(evt);
            }
        });
        CambioIdioma.add(Español);

        Ingles.setText("jMenuItem2");
        Ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InglesActionPerformed(evt);
            }
        });
        CambioIdioma.add(Ingles);

        Acesebilidad.add(CambioIdioma);

        jMenuBar1.add(Acesebilidad);

        Editar.setText("Editar");

        jMenuItem1Buscar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK | java.awt.event.InputEvent.META_DOWN_MASK));
        jMenuItem1Buscar.setText("NuevoProducto");
        jMenuItem1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1BuscarActionPerformed(evt);
            }
        });
        Editar.add(jMenuItem1Buscar);

        jMenuBar1.add(Editar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Añadir1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addGap(52, 52, 52)
                        .addComponent(Restar1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(VerProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Añadir1)
                    .addComponent(Restar1))
                .addGap(18, 18, 18)
                .addComponent(VerProducto)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Acción al pulsar botón "Añadir". Incrementa la cantidad del producto seleccionado en 1 y actualiza la tabla.
     *
     * @param evt Evento de acción del botón
     */
    private void Añadir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Añadir1ActionPerformed
        // TODO add your handling code here:
        Controlador.modifiacarCantidad(cogerElementoActual(), 1);
        actualizarList();
    }//GEN-LAST:event_Añadir1ActionPerformed
    /**
     * Acción al pulsar botón "Restar". Decrementa la cantidad del producto seleccionado en 1 y actualiza la tabla.
     *
     * @param evt Evento de acción del botón
     */
    private void Restar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restar1ActionPerformed
        // TODO add your handling code here:
        Controlador.modifiacarCantidad(cogerElementoActual(), -1);
        actualizarList();

    }//GEN-LAST:event_Restar1ActionPerformed
    /**
     * Acción al seleccionar idioma Español en el menú. Cambia el locale a español y actualiza todos los textos de la UI.
     *
     * @param evt Evento de acción del menú
     */
    private void VerProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerProductoActionPerformed
        // TODO add your handling code here:
        Producto p = cogerElementoActual();
        if (p == null) {
            return;

        }
        this.dispose();
        ProductoFicha pr = new ProductoFicha(p, user, ResurceBundle.getIdiomaActual());
        pr.setVisible(true);
        pr.setLocationRelativeTo(null);
    }//GEN-LAST:event_VerProductoActionPerformed
    /**
     * Acción al seleccionar idioma Español en el menú. Cambia el locale a español y actualiza todos los textos de la UI.
     *
     * @param evt Evento de acción del menú
     */
    private void EspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspañolActionPerformed
        // TODO add your handling code here:
        ResurceBundle.setLocale(ResurceBundle.spanish);
        actualizarElementosIdioma();
    }//GEN-LAST:event_EspañolActionPerformed
    /**
     * Acción al seleccionar idioma Inglés en el menú. Cambia el locale a inglés y actualiza todos los textos de la UI.
     *
     * @param evt Evento de acción del menú
     */
    private void InglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InglesActionPerformed
        // TODO add your handling code here:
        ResurceBundle.setLocale(ResurceBundle.english);
        actualizarElementosIdioma();
    }//GEN-LAST:event_InglesActionPerformed
    /**
     * Acción al seleccionar "Ir a Menú". Cierra esta ventana y abre la pantalla principal.
     *
     * @param evt Evento de acción del menú
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Controlador.goPrincipal(this, user, ResurceBundle.getIdiomaActual());
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    /**
     * Acción al seleccionar "Nuevo Producto". Abre la ventana para crear un nuevo producto.
     *
     * @param evt Evento de acción del menú
     */
    private void jMenuItem1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1BuscarActionPerformed
        // TODO add your handling code here:
        Controlador.goNuevoProducto(this, user, ResurceBundle.getIdiomaActual());
    }//GEN-LAST:event_jMenuItem1BuscarActionPerformed
    /**
     * Obtiene el producto seleccionado en la tabla. Valida que la lista no esté vacía y que haya una fila seleccionada.
     *
     * @return Producto seleccionado, o null si no hay selección válida
     */
    private Producto cogerElementoActual() {
        if (productos == null || productos.isEmpty()) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.noProducts.title"), // "Error"
                    ResurceBundle.t("dialog.noProducts.message"), // "No hay productos en la lista"
                    JOptionPane.ERROR_MESSAGE
            );
            return null;
        }

        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.noSelection.title"), // "Sin selección"
                    ResurceBundle.t("dialog.noSelection.message"), // "Selecciona un producto de la tabla"
                    JOptionPane.INFORMATION_MESSAGE
            );
            return null;
        }

        int filaModelo = jTable1.convertRowIndexToModel(fila);
        return productos.get(filaModelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CategoriaProducto(null, null, false, null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acesebilidad;
    private javax.swing.JButton Añadir1;
    private javax.swing.JMenu CambioIdioma;
    private javax.swing.JMenu Editar;
    private javax.swing.JMenuItem Español;
    private javax.swing.JMenuItem Ingles;
    private javax.swing.JButton Restar1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton VerProducto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1Buscar;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    /**
     * Actualiza los textos de los elementos de la UI según el idioma actual.
     * Se llama cuando cambia el idioma o al inicializar la ventana.
     */
    private void actualizarElementosIdioma() {
        /* Titulo.setText(ResurceBundle.t("login.title"));
        UserLabel.setText(ResurceBundle.t("label.userOrEmail"));
        userPane.setToolTipText(ResurceBundle.t("tooltip.userOrEmail"));
        password.setText(ResurceBundle.t("label.password"));        
        passwordPane.setToolTipText(ResurceBundle.t("tooltip.password"));
        Enviar.setText(ResurceBundle.t("button.next"));
        recuperarContrasenaBotton.setText(ResurceBundle.t("button.recoverPassword"));
        nuevoUsuario.setText(ResurceBundle.t("button.newUser"));*/
        //   adir1.setText(ResurceBundle.t("button.add"));                  // Añadir
        //AñadirListaCompra.setText(ResurceBundle.t("label.shoppingList"));// Ver lista de compra
        //EliminarProducto.setText(ResurceBundle.t("button.delete"));      // Eliminar
        if (cat) {
            Titulo.setText(ResurceBundle.t("label.category"));

        } else {
            Titulo.setText(ResurceBundle.t("label.results"));//CUANDO VIENE DE RESULTADOS

        }
        Añadir1.setText(ResurceBundle.t("button.add"));                  // Añadir

        Restar1.setText(ResurceBundle.t("button.decreaseQuantity"));
        VerProducto.setText(ResurceBundle.t("label.viewByProduct"));
        // Menú
        jMenu1.setText(ResurceBundle.t("menu.navigation"));
        jMenuItem2.setText(ResurceBundle.t("menuItem.goToMenu"));
        //IDIOMA CAMBIAR
        Acesebilidad.setText(ResurceBundle.t("menu.accessibility"));  // "Accesibilidad"
        CambioIdioma.setText(ResurceBundle.t("menu.language"));     // "Idioma"
        Español.setText(ResurceBundle.t("language.spanish"));  // "Español"
        Ingles.setText(ResurceBundle.t("language.english"));   // "English"
//EDIT
        Editar.setText(ResurceBundle.t("menu.edit"));
        jMenuItem1Buscar.setText(ResurceBundle.t("button.newProduct"));
    }
    /**
     * Actualiza el contenido de la tabla con los productos de la lista actual.
     * Limpia la tabla anterior, valida que haya productos y llena las filas.
     * Cada fila contiene: Nombre, Categoría, Cantidad, Cantidad Mínima, Fecha Caducidad.
     */
    private void actualizarList() {

        if (productos == null || productos.isEmpty()) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.noResults.title"), // o texto directo
                    ResurceBundle.t("dialog.noResults.message"), // "No hay elementos que mostrar..."
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Obtener el modelo de la tabla
        javax.swing.table.DefaultTableModel modelo
                = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        // Limpiar la tabla
        modelo.setRowCount(0);

        // Rellenar filas desde la lista productos
        for (Producto p : productos) {

            modelo.addRow(new Object[]{
                p.getNombre(),
                p.getIdCategoria().getNombre(), // categoría
                p.getCantidad(),
                p.getCantidadMinDeseada(),
                Fechas.formatearFecha(p.getFechaCaducidad())
            });
        }
    }

}
