/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Dao.Daos.DaoLogs;
import Dao.Daos.DaoUser;
import Dao.Modelo.Usuarios;
import Recursos.ElementosPersonalizados.*;
import Recursos.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HugoJB
 */
public class InicioSesion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InicioSesion.class.getName());

    /**
     * Crea el formulario de inicio de sesión. Aplica el idioma, configura colores y el Enter en el campo contraseña.
     *
     * @param idioma Código de idioma a aplicar (por ejemplo "es" o "en").
     */
    public InicioSesion(String idioma) {
        initComponents();
        getContentPane().setBackground(new Color(30, 30, 35));   // en el JFrame
// o en tu panel principal:
//panelPrincipal.setBackground(new Color(30, 30, 35));
        ResurceBundle.setLocale(idioma);

        actualizarElementosIdioma();
        Controlador.Controlador.configurarEnter(passwordPane, this::siguiente);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new LabelTitulo("");
        UserLabel = new LabelBonito("");
        jScrollPane1 = new javax.swing.JScrollPane();
        userPane = new TextPaneBonito();
        jScrollPane2 = new javax.swing.JScrollPane();
        passwordPane = new TextPaneBonito();
        password = new LabelBonito("");
        Enviar = new BotonBonito("");
        recuperarContrasenaBotton = new BotonBonito("");
        nuevoUsuario = new BotonBonito("");
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ExitOption = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenu();
        Restablecer = new javax.swing.JMenuItem();
        Acesebilidad = new javax.swing.JMenu();
        CambioIdioma = new javax.swing.JMenu();
        Español = new javax.swing.JMenuItem();
        Ingles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setText("fedsqwwgfdssdggsdgsdfgg");

        UserLabel.setText("jLabel1");

        jScrollPane1.setViewportView(userPane);

        jScrollPane2.setViewportView(passwordPane);

        password.setText("jLabel1");

        Enviar.setText("jButton1");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        recuperarContrasenaBotton.setText("jButton1");
        recuperarContrasenaBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recuperarContrasenaBottonActionPerformed(evt);
            }
        });

        nuevoUsuario.setText("jButton1");
        nuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoUsuarioActionPerformed(evt);
            }
        });

        jMenu1.setText("Ir a");

        ExitOption.setText("Exit");
        ExitOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitOptionActionPerformed(evt);
            }
        });
        jMenu1.add(ExitOption);

        jMenuBar1.add(jMenu1);

        Editar.setText("Editar");

        Restablecer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK | java.awt.event.InputEvent.META_DOWN_MASK));
        Restablecer.setText("Rescatblecer");
        Restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestablecerActionPerformed(evt);
            }
        });
        Editar.add(Restablecer);

        jMenuBar1.add(Editar);

        Acesebilidad.setText("Acesibilidad");

        CambioIdioma.setText("jMenu2");

        Español.setText("jMenuItem1");
        Español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspañolActionPerformed(evt);
            }
        });
        CambioIdioma.add(Español);

        Ingles.setText("jMenuItem2");
        Ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InglesActionPerformed(evt);
            }
        });
        CambioIdioma.add(Ingles);

        Acesebilidad.add(CambioIdioma);

        jMenuBar1.add(Acesebilidad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(recuperarContrasenaBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Enviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(nuevoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(Enviar)
                .addGap(18, 18, 18)
                .addComponent(recuperarContrasenaBotton)
                .addGap(18, 18, 18)
                .addComponent(nuevoUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Acción del botón Enviar. Delegada al método {@link #siguiente()} para reutilizar lógica.
     *
     * @param evt Evento de acción del botón.
     */
    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        siguiente();


    }//GEN-LAST:event_EnviarActionPerformed
    /**
     * Lógica principal de inicio de sesión. Valida campos, consulta usuario en BD y, si es correcto, abre la ventana principal.
     */
    public void siguiente() {
        // TODO add your handling code here:
        String nombreString = userPane.getText().trim();
        String contrasenia = passwordPane.getText().trim();

        if (nombreString.isEmpty()) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("login.title"),
                    ResurceBundle.t("error.login.userRequired"),
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (contrasenia.isEmpty()) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("login.title"),
                    ResurceBundle.t("error.login.passwordRequired"),
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        //YA TENGO TODO

        Usuarios usuario = DaoUser.buscarPorCredenciales(nombreString, contrasenia);

        if (usuario == null) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("login.title"),
                    ResurceBundle.t("error.login.credentials"),
                    JOptionPane.ERROR_MESSAGE
            );
        } else {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("login.welcome.title"),
                    ResurceBundle.t("login.welcome.message") + " " + usuario.getNombre(),
                    JOptionPane.INFORMATION_MESSAGE
            );
            DaoLogs.registrarInicio(usuario);//LO REGISTRA EL LOG
            this.dispose();
            // MENU PRINCIPAL CON USER NOT NULL
            Principal principal = new Principal(usuario, ResurceBundle.getIdiomaActual());
            principal.setVisible(true);
        }
    }
     /**
     * Abre la ventana de recuperación de contraseña.
     *
     * @param evt Evento del botón "Recuperar contraseña".
     */
    private void recuperarContrasenaBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recuperarContrasenaBottonActionPerformed
        // TODO add your handling code here:
        this.dispose();  // CIERRA ACTUAL

        RecuperarContraseña recuperarFrame = new RecuperarContraseña(ResurceBundle.getIdiomaActual());
        recuperarFrame.setVisible(true);
        recuperarFrame.setLocationRelativeTo(null);  // Centra en pantalla

    }//GEN-LAST:event_recuperarContrasenaBottonActionPerformed

        /**
     * Abre el diálogo de registro de nuevo usuario.
     *
     * @param evt Evento del botón "Nuevo usuario".
     */

    private void nuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoUsuarioActionPerformed
        // TODO add your handling code here:
        RegistroDialog dialog = new RegistroDialog(this, true);
        dialog.setVisible(true);

    }//GEN-LAST:event_nuevoUsuarioActionPerformed
/**
     * Cierra la aplicación cuando se pulsa la opción de salida.
     *
     * @param evt Evento del elemento de menú "Exit".
     */
    private void ExitOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitOptionActionPerformed
        // TODO add your handling code here:
        System.exit(0);//SALE DEL PROGAMA
    }//GEN-LAST:event_ExitOptionActionPerformed
/**
     * Restablece los campos del formulario de login.
     *
     * @param evt Evento del elemento de menú "Restablecer".
     */
    private void RestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestablecerActionPerformed
        // TODO add your handling code here:
        restablecerFormulario();
    }//GEN-LAST:event_RestablecerActionPerformed
  /**
     * Cambia el idioma a español y actualiza los textos.
     *
     * @param evt Evento del menú Español.
     */
    private void EspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspañolActionPerformed
        // TODO add your handling code here:
        ResurceBundle.setLocale(ResurceBundle.spanish);
        actualizarElementosIdioma();
        System.out.println("patata");
    }//GEN-LAST:event_EspañolActionPerformed
/**
     * Cambia el idioma a inglés y actualiza los textos.
     *
     * @param evt Evento del menú Inglés.
     */
    private void InglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InglesActionPerformed
        // TODO add your handling code here:
        ResurceBundle.setLocale(ResurceBundle.english);
        actualizarElementosIdioma();
        //  System.out.println("patata inglesa"+ResurceBundle.getIdiomaActual());
    }//GEN-LAST:event_InglesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InicioSesion(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acesebilidad;
    private javax.swing.JMenu CambioIdioma;
    private javax.swing.JMenu Editar;
    private javax.swing.JButton Enviar;
    private javax.swing.JMenuItem Español;
    private javax.swing.JMenuItem ExitOption;
    private javax.swing.JMenuItem Ingles;
    private javax.swing.JMenuItem Restablecer;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nuevoUsuario;
    private javax.swing.JLabel password;
    private javax.swing.JTextPane passwordPane;
    private javax.swing.JButton recuperarContrasenaBotton;
    private javax.swing.JTextPane userPane;
    // End of variables declaration//GEN-END:variables

    private void actualizarElementosIdioma() {
        // Componentes principales
        Titulo.setText(ResurceBundle.t("login.title"));
        UserLabel.setText(ResurceBundle.t("label.userOrEmail"));
        userPane.setToolTipText(ResurceBundle.t("tooltip.userOrEmail"));
        password.setText(ResurceBundle.t("label.password"));
        passwordPane.setToolTipText(ResurceBundle.t("tooltip.password"));
        Enviar.setText(ResurceBundle.t("button.next"));
        recuperarContrasenaBotton.setText(ResurceBundle.t("button.recoverPassword"));
        nuevoUsuario.setText(ResurceBundle.t("button.newUser"));

        // MENÚS - TODOS los componentes del menú
        jMenu1.setText(ResurceBundle.t("menu.navigation"));
        ExitOption.setText(ResurceBundle.t("menuItem.exit"));
        Editar.setText(ResurceBundle.t("menu.edit"));
        Restablecer.setText(ResurceBundle.t("button.resetForm"));

        // ACCESIBILIDAD E IDIOMA - AQUÍ ESTABA EL PROBLEMA
        Acesebilidad.setText(ResurceBundle.t("menu.accessibility"));
        CambioIdioma.setText(ResurceBundle.t("menu.language"));
        Español.setText(ResurceBundle.t("language.spanish"));
        Ingles.setText(ResurceBundle.t("language.english"));
    }

    private void restablecerFormulario() {
        userPane.setText("");
        passwordPane.setText("");
        userPane.requestFocus();  // Pone el cursor en el campo usuario
    }

}
