/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import Dao.Daos.DaoCategoria;
import Dao.Daos.DaoProducto;
import Dao.Modelo.Categoria;
import Dao.Modelo.Producto;
import Dao.Modelo.Usuarios;
import Recursos.ElementosPersonalizados.*;
import Recursos.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 * Ventana para crear un nuevo producto en el inventario.
 * Permite introducir nombre, cantidad, categoría, fecha de caducidad
 * y si pertenece a la lista de la compra.
 *
 * @author HugoJB
 */
public class NuevoProducto extends javax.swing.JFrame {

    /**
     * Usuario autenticado propietario del nuevo producto.
     */
    private Usuarios user;

    /**
     * Selector de fecha para la fecha de caducidad del producto.
     */
    private com.github.lgooddatepicker.components.DatePicker FechaPicker;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NuevoProducto.class.getName());

    /**
     * Crea el formulario de nuevo producto.
     * Valida la existencia de usuario, aplica idioma,
     * inicializa componentes y configura el DatePicker.
     *
     * @param user   Usuario autenticado. Si es null, se redirige a InicioSesion.
     * @param idioma Código de idioma a aplicar (por ejemplo "es" o "en").
     */
    public NuevoProducto(Usuarios user, String idioma) {
        this.user = user;//ANTES DE HACR NADA SI NO HAY USER NO FUNCIONA

        if (user == null) {
            CuadroDiologo.mostrarAviso(this, "Sin usuario no se puede ejecutar", "no se pude seguir", JOptionPane.ERROR_MESSAGE);
            this.dispose();
            InicioSesion inicioSesion = new InicioSesion(idioma);
            inicioSesion.setVisible(true);
            return;
        }
        FechaPicker = new com.github.lgooddatepicker.components.DatePicker();

    // Opcional: formato
        FechaPicker.getSettings().setFormatForDatesCommonEra("dd/MM/yyyy");//PARA LA FECHA
        initComponents();
        getContentPane().setBackground(new Color(30, 30, 35));   // en el JFrame
    // o en tu panel principal:
    //panelPrincipal.setBackground(new Color(30, 30, 35));

        ResurceBundle.setLocale(idioma);
        actualizarElementosIdioma();

        //PARA LOS ENTER
        Controlador.configurarEnter(CatageriaEditText, this::Guardar);//LAMA A ESTE METODO
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreL = new LabelBonito("");
        jScrollPane1 = new javax.swing.JScrollPane();
        NombreEd = new TextPaneBonito();
        jScrollPane2 = new javax.swing.JScrollPane();
        CantidadEdit = new TextPaneBonito();
        CantidadLabel = new LabelBonito("");
        Titulo = new LabelTitulo("");
        CatageriaLabel = new LabelBonito("");
        MininmoDesadoLabel = new LabelBonito("");
        jScrollPane3 = new javax.swing.JScrollPane();
        MininmoDesadoEdit = new TextPaneBonito();
        jScrollPane4 = new javax.swing.JScrollPane();
        CatageriaEditText = new TextPaneBonito();
        AddButon = new BotonBonito("");
        FechaCaducidadLabel = new LabelBonito("");
        jScrollPane6 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        editar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Restablecer = new javax.swing.JMenuItem();
        PonerListaCompra = new javax.swing.JMenu();
        chebos = new javax.swing.JCheckBoxMenuItem();
        Acesebilidad = new javax.swing.JMenu();
        CambioIdioma = new javax.swing.JMenu();
        Español = new javax.swing.JMenuItem();
        Ingles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreL.setText("jLabel1");

        jScrollPane1.setViewportView(NombreEd);

        jScrollPane2.setViewportView(CantidadEdit);

        CantidadLabel.setText("jLabel1");

        Titulo.setText("fedsqwwgfdssdggsdgsdfgg");

        CatageriaLabel.setText("jLabel1");

        MininmoDesadoLabel.setText("jLabel1");

        jScrollPane3.setViewportView(MininmoDesadoEdit);

        jScrollPane4.setViewportView(CatageriaEditText);

        AddButon.setText("jButton1");
        AddButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButonActionPerformed(evt);
            }
        });

        FechaCaducidadLabel.setText("jLabel1");

        jMenu1.setText("Ir a");

        jMenuItem2.setText("Menu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        editar.setText("Editar");

        jMenuItem1.setText("Guardar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        editar.add(jMenuItem1);

        Restablecer.setText("Restablecer");
        Restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestablecerActionPerformed(evt);
            }
        });
        editar.add(Restablecer);

        jMenuBar1.add(editar);

        PonerListaCompra.setText("lISTA COMPRA");

        chebos.setSelected(true);
        chebos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chebosActionPerformed(evt);
            }
        });
        PonerListaCompra.add(chebos);

        jMenuBar1.add(PonerListaCompra);

        Acesebilidad.setText("Acesibilidad");

        CambioIdioma.setText("jMenu2");

        Español.setText("jMenuItem1");
        Español.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspañolActionPerformed(evt);
            }
        });
        CambioIdioma.add(Español);

        Ingles.setText("jMenuItem2");
        Ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InglesActionPerformed(evt);
            }
        });
        CambioIdioma.add(Ingles);

        Acesebilidad.add(CambioIdioma);

        jMenuBar1.add(Acesebilidad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddButon, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CantidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreL, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CatageriaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(MininmoDesadoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(FechaCaducidadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CantidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MininmoDesadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CatageriaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FechaCaducidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(AddButon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView( FechaPicker);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void RestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestablecerActionPerformed
        // TODO add your handling code here:
        restablecer();
    }//GEN-LAST:event_RestablecerActionPerformed
   /**
     * Acción del botón principal "Guardar".
     * Llama al método {@link #Guardar()} y, si devuelve true,
     * finaliza la acción sin más.
     *
     * @param evt Evento de acción del botón.
     */
    private void AddButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButonActionPerformed
        if (Guardar())
            return;
    }//GEN-LAST:event_AddButonActionPerformed
    /**
     * Realiza la validación de datos, construcción del objeto Producto
     * y persistencia en base de datos.
     *
     * @return true si la operación termina correctamente o por validación,
     *         false si hubo un error genérico tras capturar excepciones.
     */
    private boolean Guardar() {
        // TODO add your handling code here:
        // Validar campos no vacíos
        if (!validarFormulario()) {
            return true;
        }
        try {
            // Obtener valores del formulario
            String nombre = NombreEd.getText().trim();
            int cantidad = Integer.parseInt(CantidadEdit.getText().trim());
            int cantidadMin = Integer.parseInt(MininmoDesadoEdit.getText().trim());
            String categoriaNombre = CatageriaEditText.getText().trim();
            // Validar cantidad no negativa
            if (cantidad < 0) {
                CuadroDiologo.mostrarAviso(
                        this,
                        ResurceBundle.t("dialog.invalidQuantity.title"),
                        ResurceBundle.t("dialog.invalidQuantity.message"),
                        JOptionPane.ERROR_MESSAGE
                );
                return true;
            }
            // Obtener categoría (crear si no existe)
            Categoria categoria = obtenerOCrearCategoria(categoriaNombre);
            if (categoria == null) {
                CuadroDiologo.mostrarAviso(
                        this,
                        ResurceBundle.t("dialog.error.title"),
                        ResurceBundle.t("dialog.categoryError.message"),
                        JOptionPane.ERROR_MESSAGE
                );
                return true;
            }
            // Obtener fecha de caducidad (si existe)
            java.util.Date fechaCaducidad = null;
            if (FechaPicker.getDate() != null) {
                java.time.LocalDate ld = FechaPicker.getDate();
                java.util.Calendar cal = java.util.Calendar.getInstance();
                cal.set(ld.getYear(), ld.getMonthValue() - 1, ld.getDayOfMonth());
                fechaCaducidad = cal.getTime();
            }
            // Crear nuevo Producto
            Producto nuevoProducto = new Producto();
            nuevoProducto.setNombre(nombre);
            nuevoProducto.setCantidad(cantidad);
            nuevoProducto.setCantidadMinDeseada(cantidadMin);
            nuevoProducto.setIdCategoria(categoria);
            nuevoProducto.setFechaCaducidad(fechaCaducidad);
            nuevoProducto.setListaCompra(false);  // Por defecto, no en lista de compra
            nuevoProducto.setIdUser(user);  // Asignamos el usuario actual
            nuevoProducto.setListaCompra(chebos.isSelected());
            // Guardar en BD
            DaoProducto dao = new DaoProducto();
            dao.insert(nuevoProducto);
            // Éxito: mostrar aviso y restablecer formulario
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.success.title"),
                    ResurceBundle.t("dialog.productCreated.message"),
                    JOptionPane.INFORMATION_MESSAGE
            );
            restablecer();//PARA METER OTRO USER
            return true;
        } catch (NumberFormatException ex) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.invalidInput.title"),
                    ResurceBundle.t("dialog.invalidInput.message"),
                    JOptionPane.ERROR_MESSAGE
            );
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.error.title"),
                    ResurceBundle.t("dialog.saveError.message"),
                    JOptionPane.ERROR_MESSAGE
            );
        }
        return false;
    }
  /**
     * Acción del menú "Guardar".
     * Reutiliza la lógica del botón principal llamando a {@link #Guardar()}.
     *
     * @param evt Evento de acción del elemento de menú.
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Guardar();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /**
     * SOBRA
     *
     * @param evt
     */
    private void chebosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chebosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_chebosActionPerformed
 /**
     * Cambia el idioma de la interfaz a español y actualiza los textos.
     *
     * @param evt Evento del menú Español.
     */
    private void EspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspañolActionPerformed
        // TODO add your handling code here:
        ResurceBundle.setLocale(ResurceBundle.spanish);
        actualizarElementosIdioma();
    }//GEN-LAST:event_EspañolActionPerformed
 /**
     * Cambia el idioma de la interfaz a inglés y actualiza los textos.
     *
     * @param evt Evento del menú Inglés.
     */
    private void InglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InglesActionPerformed
        // TODO add your handling code here:
        ResurceBundle.setLocale(ResurceBundle.english);
        actualizarElementosIdioma();
    }//GEN-LAST:event_InglesActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Controlador.goPrincipal(this, user, ResurceBundle.getIdiomaActual());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     *//*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*     java.awt.EventQueue.invokeLater(() -> new NuevoProducto(null).setVisible(true));
    }
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Acesebilidad;
    private javax.swing.JButton AddButon;
    private javax.swing.JMenu CambioIdioma;
    private javax.swing.JTextPane CantidadEdit;
    private javax.swing.JLabel CantidadLabel;
    private javax.swing.JTextPane CatageriaEditText;
    private javax.swing.JLabel CatageriaLabel;
    private javax.swing.JMenuItem Español;
    private javax.swing.JLabel FechaCaducidadLabel;
    private javax.swing.JMenuItem Ingles;
    private javax.swing.JTextPane MininmoDesadoEdit;
    private javax.swing.JLabel MininmoDesadoLabel;
    private javax.swing.JTextPane NombreEd;
    private javax.swing.JMenu PonerListaCompra;
    private javax.swing.JMenuItem Restablecer;
    private javax.swing.JLabel Titulo;
    private javax.swing.JCheckBoxMenuItem chebos;
    private javax.swing.JMenu editar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel nombreL;
    // End of variables declaration//GEN-END:variables
private void actualizarElementosIdioma() {

        // Título
        Titulo.setText(ResurceBundle.t("label.newProduct"));

        // Labels
        nombreL.setText(ResurceBundle.t("table.product.name"));
        CantidadLabel.setText(ResurceBundle.t("label.quantity"));
        MininmoDesadoLabel.setText(ResurceBundle.t("table.product.minQuantity"));
        CatageriaLabel.setText(ResurceBundle.t("table.product.category"));

        // Tooltips campos
        NombreEd.setToolTipText(ResurceBundle.t("label.addProductName"));
        CantidadEdit.setToolTipText(ResurceBundle.t("label.addProductQuantity"));
        MininmoDesadoEdit.setToolTipText(ResurceBundle.t("label.addProductMinQuantity"));
        CatageriaEditText.setToolTipText(ResurceBundle.t("label.addProductCategory"));

        // Botón principal
        AddButon.setText(ResurceBundle.t("button.saveProduct"));

        // Menú
        jMenu1.setText(ResurceBundle.t("menu.navigation"));
        jMenuItem2.setText(ResurceBundle.t("menuItem.goToMenu"));
        editar.setText(ResurceBundle.t("menu.edit"));
        jMenuItem1.setText(ResurceBundle.t("button.saveProduct"));
        Restablecer.setText(ResurceBundle.t("button.resetForm"));
        FechaCaducidadLabel.setText(ResurceBundle.t("label.dateExpiraton"));
        PonerListaCompra.setText(ResurceBundle.t("label.shoppingListTitle"));

        //IDIOMA CAMBIAR
        Acesebilidad.setText(ResurceBundle.t("menu.accessibility"));  // "Accesibilidad"
        CambioIdioma.setText(ResurceBundle.t("menu.language"));     // "Idioma"
        Español.setText(ResurceBundle.t("language.spanish"));  // "Español"
        Ingles.setText(ResurceBundle.t("language.english"));   // "English"
    }

/**
     * Valida que los campos obligatorios del formulario no estén vacíos
     * y muestra mensajes de aviso en caso necesario.
     *
     * @return true si todos los campos son válidos, false en caso contrario.
     */
    private boolean validarFormulario() {
        if (NombreEd.getText().trim().isEmpty()) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.requiredField.title"),
                    ResurceBundle.t("dialog.fieldName.message"),
                    JOptionPane.WARNING_MESSAGE
            );
            return false;
        }

        if (CantidadEdit.getText().trim().isEmpty()) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.requiredField.title"),
                    ResurceBundle.t("dialog.fieldQuantity.message"),
                    JOptionPane.WARNING_MESSAGE
            );
            return false;
        }

        if (MininmoDesadoEdit.getText().trim().isEmpty()) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.requiredField.title"),
                    ResurceBundle.t("dialog.fieldMinQuantity.message"),
                    JOptionPane.WARNING_MESSAGE
            );
            return false;
        }

        if (CatageriaEditText.getText().trim().isEmpty()) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.requiredField.title"),
                    ResurceBundle.t("dialog.fieldCategory.message"),
                    JOptionPane.WARNING_MESSAGE
            );
            return false;
        }

        return true;
    }

  /**
     * Obtiene una categoría por nombre desde la base de datos o la crea
     * si no existe aún y la devuelve.
     *
     * @param nombre Nombre de la categoría a buscar o crear.
     * @return Categoría existente o recién creada, nunca null.
     */
    private Categoria obtenerOCrearCategoria(String nombre) {
        Categoria categoria = DaoCategoria.getCategoriaForNombre(nombre);

        if (categoria == null) {
            // Crear nueva
            categoria = new Categoria();
            categoria.setNombre(nombre);
            new DaoCategoria().insert(categoria);//LA crea 
            return categoria;//La devuelve
        } else {
            return categoria;
        }
    }

 
    /**
     * Restablece el formulario a valores por defecto.
     * Borra los campos, limpia la fecha y pone el foco en el nombre.
     */
    private void restablecer() {
        NombreEd.setText("");
        CantidadEdit.setText("");
        MininmoDesadoEdit.setText("");
        CatageriaEditText.setText("");
        FechaPicker.setDate(null);
        NombreEd.requestFocus();
    }

}
