/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Dao.Daos.*;
import Dao.Modelo.Categoria;
import Dao.Modelo.Producto;
import Dao.Modelo.Usuarios;
import Recursos.ElementosPersonalizados.*;
import Recursos.*;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HugoJB
 */
public class Principal extends javax.swing.JFrame {

    List<Producto> listCaducidad;
    private final Usuarios user;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal(Usuarios usuario) {
        this.user = usuario;
        if (user == null) {
            CuadroDiologo.mostrarAviso(this, "Sin usuario no se puede ejecutar", "no se pude seguir", JOptionPane.ERROR_MESSAGE);
            //System.exit(1); //ME CARGO EL PROGAMA 
            //MEJOR ME VOY AL LOGIN
            this.dispose();
            InicioSesion inicioSesion = new InicioSesion();
            inicioSesion.setVisible(true);//VA INICIO SESION
            //  System.exit(0);
            return;
        }
        ResurceBundle.setLocale(ResurceBundle.spanish);
        initComponents();
        getContentPane().setBackground(new Color(30, 30, 35));   // en el JFrame

// o en tu panel principal:
//panelPrincipal.setBackground(new Color(30, 30, 35));
        actualizarElementosIdioma();
        actualizarTablaCaducidad();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new PanelBonito();
        Buscar = new BotonBonito("");
        NuevoProductoBotton = new BotonBonito("");
        CaducidadProsima = new LabelTitulo("");
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new TableBonito();
        VerProductosPorCategoria = new BotonBonito("");
        VerProductoSelecionado1 = new BotonBonito("");
        VerListaCompra = new BotonBonito("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Buscar.setText("jButton1");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        NuevoProductoBotton.setText("jButton1");
        NuevoProductoBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoProductoBottonActionPerformed(evt);
            }
        });

        CaducidadProsima.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                ResurceBundle.t("table.product.name") , ResurceBundle.t("table.product.category"),  ResurceBundle.t("table.product.quantity"),  ResurceBundle.t("table.product.minQuantity")
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jScrollPane1.getViewport().setBackground(new Color(45, 45, 55));
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(80, 80, 95)));

        VerProductosPorCategoria.setText("jButton1");
        VerProductosPorCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerProductosPorCategoriaActionPerformed(evt);
            }
        });

        VerProductoSelecionado1.setText("jButton1");
        VerProductoSelecionado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerProductoSelecionado1ActionPerformed(evt);
            }
        });

        VerListaCompra.setText("jButton1");
        VerListaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerListaCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NuevoProductoBotton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                    .addComponent(CaducidadProsima, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VerProductosPorCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VerListaCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(157, 157, 157)
                    .addComponent(VerProductoSelecionado1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(114, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(NuevoProductoBotton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(CaducidadProsima, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(VerProductosPorCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(VerListaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(487, Short.MAX_VALUE)
                    .addComponent(VerProductoSelecionado1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(295, 295, 295)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        String texto = JOptionPane.showInputDialog(
                this,
                ResurceBundle.t("search.prompt"), // "Introduce nombre de producto (vacío = todos)"
                ResurceBundle.t("button.search"), // título
                JOptionPane.QUESTION_MESSAGE
        );

        // Si pulsa Cancelar o cierra el diálogo, no haces nada
        if (texto == null) {
            return;
        }

        texto = texto.trim();

        if (texto.isEmpty()) {
            // Buscar TODOS los productos del usuario actual

            List<Producto> productos = DaoProducto.buscarPorUsuario(1);

            irSegunda(productos, false);
        } else {
            // Buscar productos cuyo nombre empiece por 'texto' para ese usuario
            List<Producto> productos = Dao.Daos.DaoProducto.buscarPorNombreYUsuario(texto, user.getId());
            //  actualizarTabla(productos);
            irSegunda(productos, false);

        }
    }//GEN-LAST:event_BuscarActionPerformed
    /**
     * Va a nuevo producto y lo crea
     *
     * @param evt
     */
    private void NuevoProductoBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoProductoBottonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        NuevoProducto nv = new NuevoProducto(user);
        nv.setVisible(true);
        nv.setLocationRelativeTo(null);  // Centra en pantalla


    }//GEN-LAST:event_NuevoProductoBottonActionPerformed

    private void VerProductoSelecionado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerProductoSelecionado1ActionPerformed
        // TODO add your handling code here:
        if (listCaducidad == null || listCaducidad.isEmpty()) {
            CuadroDiologo.mostrarAviso(this, "No se puede mostrar", "La tabla esta vacia", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int fila = jTable1.getSelectedRow();

        if (fila == -1) {
            CuadroDiologo.mostrarAviso(this, "Ningún producto seleccionado", "Selecciona una fila primero", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int filaModelo = jTable1.convertRowIndexToModel(fila);

        // Obtener el Producto correspondiente de la lista
        Producto seleccionado = listCaducidad.get(filaModelo);
        this.dispose();
        ProductoFicha pr = new ProductoFicha(seleccionado);
        pr.setVisible(true);
        pr.setLocationRelativeTo(null);


    }//GEN-LAST:event_VerProductoSelecionado1ActionPerformed

    private void VerProductosPorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerProductosPorCategoriaActionPerformed
        // TODO add your handling code here:
        List<Categoria> categorias = DaoCategoria.buscarCategoriasDeUsuario(user.getId());

        if (categorias == null || categorias.isEmpty()) {
            CuadroDiologo.mostrarAviso(
                    this,
                    ResurceBundle.t("dialog.noCategories.title"), 
                    ResurceBundle.t("dialog.noCategories.message"), 
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }

        // HE ENCONTRADO CON LAMBA ESTO PARA PASAR A TO STRING
        String[] nombresCat = categorias.stream()
                .map(Categoria::getNombre) 
                .toArray(String[]::new);

        String seleccion = (String) JOptionPane.showInputDialog(
                this,
                ResurceBundle.t("dialog.chooseCategory.message"), 
                ResurceBundle.t("dialog.chooseCategory.title"), 
                JOptionPane.QUESTION_MESSAGE,
                null,
                nombresCat,
                nombresCat[0]
        );

        // Si pulsa cancelar o cierra
        if (seleccion == null) {
            return;
        }

        // Buscar la categoría seleccionada en la lista original
        Categoria categoriaElegida = categorias.stream()
                .filter(c -> c.getNombre().equals(seleccion))
                .findFirst()
                .orElse(null);

        if (categoriaElegida == null) {
            return;
        }

        // Ahora ya tienes la Categoria; aquí decides qué hacer
        // Por ejemplo, cargar productos de esa categoría:
        List<Producto> productos = DaoProducto.buscarPorCategoriaYUsuario(
                categoriaElegida.getId(), user.getId()
        );

        irSegunda(productos, true);


    }//GEN-LAST:event_VerProductosPorCategoriaActionPerformed

    private void VerListaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerListaCompraActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ListaCompra listaCompra=new ListaCompra(user);
        listaCompra.setVisible(true);
                listaCompra.setLocationRelativeTo(null);

    }//GEN-LAST:event_VerListaCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel CaducidadProsima;
    private javax.swing.JButton NuevoProductoBotton;
    private javax.swing.JButton VerListaCompra;
    private javax.swing.JButton VerProductoSelecionado1;
    private javax.swing.JButton VerProductosPorCategoria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void actualizarElementosIdioma() {
        Buscar.setText(ResurceBundle.t("button.search"));
        CaducidadProsima.setText(ResurceBundle.t("label.expiringSoon"));
        NuevoProductoBotton.setText(ResurceBundle.t("button.newProduct"));
        VerListaCompra.setText(ResurceBundle.t("label.shoppingList"));
        VerProductoSelecionado1.setText(ResurceBundle.t("button.viewSelectedProduct"));
        VerProductosPorCategoria.setText(ResurceBundle.t("label.viewByCategory"));

    }

    private void irSegunda(List<Producto> productos, boolean categoria) {
        if (productos == null) {
            CuadroDiologo.mostrarAviso(this, "No ha habido resuldatos", "No se ha podido abrir", JOptionPane.ERROR);
            return;
        }
        this.dispose();  // CIERRA ACTUAL

        CategoriaProducto cat = new CategoriaProducto(user, productos, categoria);//SIEMPRE TENGO QUE MANTENER EL USER ACTUAL
        cat.setVisible(true);
        cat.setLocationRelativeTo(null);  // Centra en pantalla
    }

    private void actualizarTablaCaducidad() {
        listCaducidad = DaoProducto.buscarTop10PorCaducidad(user.getId());
        if (listCaducidad == null || listCaducidad.isEmpty()) {
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (Producto p : listCaducidad) {
            String fechaTxt = "";
            if (p.getFechaCaducidad() != null) {
                fechaTxt = sdf.format(p.getFechaCaducidad());
            }

            modelo.addRow(new Object[]{
                p.getNombre(),
                p.getIdCategoria().getNombre(),//me flipa que se pueda hacer esto
                p.getCantidad(),
                p.getCantidadMinDeseada(),
                fechaTxt
            });

        }
    }

}
